###
POST http://localhost:7000/message/ping
Content-Type: application/json

{
  "to": "608a776586bb2a613fc7109d",
  "ping": "123"
}


###
POST http://localhost:7000/user/register
Content-Type: application/json

{
  "weixinId": "wangao",
  "username": "wangao",
  "password": "123"
}

###

POST http://localhost:7000/user/login
Content-Type: application/json

{
  "weixinId": "wangao",
  "username": "wangao",
  "password": "123"
}

###
POST http://localhost:7000/message
Content-Type: application/json

{
  "content": "Hello",
  "contentType": "TEXT",
  "messageType": "SINGLE"
}

###

POST http://localhost:7000/user/register
Content-Type: application/json

{
  "weixinId": "zhangzhi",
  "username": "zhangzhi",
  "password": "123"
}

###
GET http://localhost:7000/user
Content-Type: application/json

{
  "weixinId": "wangao"
}

###
POST http://localhost:7000/user/addfriend
Content-Type: application/json

{
  "friendId":"608a6a30fc794c6c2c85846d"
}


